// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Primeur.Data;

namespace Primeur.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Primeur.Data.Fruits", b =>
                {
                    b.Property<string>("Nom")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Variete")
                        .HasColumnType("text");

                    b.HasKey("Nom");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("Primeur.Data.Legumes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantite")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Variete")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Legumes");
                });
#pragma warning restore 612, 618
        }
    }
}
