Use ECF_PHP;
INSERT INTO `textes`(`codeTexte`, `FR`, `EN`) VALUES 
("Identification","Identification","Identification"),
("MotDePasse","Mot de Passe","Password"),
("ConfirmationMotDePasse","Confirmation du mot de passe","Confirm password"),
("Role","Role(1: user - 2: admin)","Role(1: user - 2: admin)"),
("Produits","Produits","Product"),
("Categories","Catégories","Category"),
("TexteMenu","Choisissez entre Produits et catégories","Choose between Product and Category"),
("Ajouter","Ajouter","Add"),
("Editer","Afficher","Show"),
("Modifier","Modifier","Modify"),
("Supprimer","Supprimer","Delete"),
("Libelle","Libelle","Description"),
("Prix","Prix","Price"),
("DatePeremption","Date de peremption","Expiry date"),
("CrudProduit"," un produit"," a product"),
("CrudCategorie"," une categorie"," a category"),
("Deconnecter","Deconnecter","Disconnect"),
("Pseudo","Pseudo","Alias"),
("Annuler","Annuler","Cancel"),
("ListeProduits", "Liste de produits", "List product"),
("GestionProduit", "Gestion des produits", "Product management"),
("ListeCategories", "Liste des Catégories", "List Category"),
("GestionCategories", "Gestion des catégories", "Category management"),
('Inconnue', '418: je suis une théière !','418 I\'m a teapot'),
('erreurAjouter','L\'ajout a échoué', 'Add failed'),
('erreurModifier', 'La modification a échoué','Update failed'),
('erreurSupprimer', 'La suppression a échoué','Delete failed'),
('Confirm', 'La confirmation ne correspond pas au mot de passe','Confirmation not match'),
('DoublePseudo', 'Le pseudo existe deja','Nickname already exists '),
('MdpIncorrect', 'Le mot de passe est incorrect','incorrect password'),
('MailUnkn', 'L\'adresse mail  n\'existe pas','mail unknown'),
('titreErreur', 'Une erreur est survenue','An error occurred')